Bugfix/admin vendor books
peaksoft-school/peaksoft-ebook-web pull request #30
Opened 2022-06-03 13:48 UTC by adinaiz

2022-06-04 09:00 UTC, zhumabek requested changes

2022-06-04 09:00 UTC, zhumabek commented on src/api/appFetch.js
> +      const result = responseOption?.asText
что это такое? то есть бекенд возвращает текст шоли?

2022-06-04 09:00 UTC, zhumabek commented on src/components/Admin/AdminHeader.jsx
> +      localStorage.removeItem('eBook-user-key-json')
в константу вынести надо ключ

2022-06-04 09:00 UTC, zhumabek commented on src/components/UI/AudioListener/AudioListener.jsx
> +   // console.log(audio)
коммент удалить

2022-06-04 09:00 UTC, zhumabek commented on src/components/UI/Card/AdminBookCard.jsx
> +      setTimeout(() => setShowSuccess(false), 2000)
как Бекболсун сделает само закрывающую модалку надо будет исправить а пока пусть так остается
на заметку

2022-06-04 09:00 UTC, zhumabek commented on src/components/UI/Card/AdminBookCard.jsx
> +            {showModal && (
зачем оператор   && ты ведь и так даешь как пропс isOpen

2022-06-04 09:00 UTC, zhumabek commented on src/components/UI/Card/AdminBookCard.jsx
> +            {showSuccess && (
зачем оператор   && ты ведь и так даешь как пропс isOpen

2022-06-04 09:00 UTC, zhumabek commented on src/components/UI/Card/VendorBookCard.jsx
> +                     <p>({like})</p>
amount of like or amount of likes? which one is correct? Cindrella

2022-06-04 09:00 UTC, zhumabek commented on src/pages/Admin/ApplicationsSection/ApplicationsInnerPage.jsx
> +      setTimeout(() => setShowSuccess(false), 2000)
по идее нужно очищать timeout это может привезти к memory leaks problems

2022-06-04 09:00 UTC, zhumabek commented on src/pages/Admin/ApplicationsSection/ApplicationsInnerPage.jsx
> +         {showModal && (
оператор &&

2022-06-04 09:00 UTC, zhumabek commented on src/store/admin-slice.js
> +         navigateAfterSuccessDelete()
а шо нет сообщения типа успешно удалили вендора?

2022-06-04 11:56 UTC, adinaiz commented on src/api/appFetch.js
> +      const result = responseOption?.asText
da

2022-06-05 04:03 UTC, zhumabek requested changes

2022-06-05 04:03 UTC, zhumabek commented on src/pages/Admin/ApplicationsSection/ApplicationsInnerPage.jsx
> +      return () => clearTimeout(setShowSuccess())
Не правильно очищается таймер

2022-06-05 04:03 UTC, zhumabek commented on src/components/UI/Card/VendorBookCard.jsx
> +                     <p>({like})</p>
what about likes?

2022-06-05 06:14 UTC, zhumabek requested changes

2022-06-05 06:14 UTC, zhumabek commented on src/components/UI/Card/AdminBookCard.jsx
> +      setTimeout(() => setShowSuccess(false), 2000)
тут тоже забыла очистить(((

2022-06-05 06:22 UTC, merged